### ISSUE TITLE
Tiles occasionally jump abruptly 

### ISSUE THREAD

**Issue by jasonpang** [24game/twentyfour#9]
They won't jump abruptly the first time, but sometimes if you move your mouse while the animation is occurring, the tiles jump abruptly from the animating location to the final location.

**Comment by cbass10liu** [comment]
Also I find that this frequently happens if you slowly drag a tile and release it midway.

**Comment by jasonpang** [comment]
Fixed by: https://github.com/24game/twentyfour/commit/5237943d32e0790afe52fb3fec5f45e6fc534f94
